### ISSUE TITLE
Service returns error for all requests

### ISSUE THREAD

**Issue by ragesoss** [jurkan/whoCOLOR#2]
For the last few weeks, no data is coming through from the whoCOLOR api. Any request results in `{"success":false,"reason":"Wikiwho JSON was null"}`.

**Comment by faflo** [comment]
should be fixed now. we simply ran out of space. the new version (on a bigger server) will be up soon so this won't be an issue anymore. let me know if it works.

**Comment by ragesoss** [comment]
Yep, works now. Thanks!
