### ISSUE TITLE
HTTPS certificate expired for whocolor.net

### ISSUE THREAD

**Issue by ragesoss** [jurkan/whoCOLOR#4]
The security cert for whocolor.net has expired. (I've switched the Wiki Ed  Dashboard authorship viewer client to http in the meantime: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/10de8d10055b8149ecfb327b2a5be30502c6b6d2)

**Comment by wikiwho** [comment]
yes, sorry for that, there was a hickup, it should work again soon.

**Comment by ragesoss** [comment]
I've set up the whocolor scripts on tools.wmflabs.org to work around the certs issue. I had to change the Wikipedia endpoints to https, but otherwise it seems to work just fine this way.

Forked version here: https://github.com/WikiEducationFoundation/whoCOLOR
API endpoint here: https://tools.wmflabs.org/wikiedudashboard/whocolor/index.php

**Comment by faflo** [comment]
great, btw, you could also make it use the new wikiwho  API we have put up, should be even faster and more accurate:  https://api.wikiwho.net/api/v1.0.0-beta/

**Comment by ragesoss** [comment]
@faflo cool! I was playing around with that a little bit, but wasn't sure of the status and the output looked significantly different. It's still compatible with the whocolor transformation?

**Comment by faflo** [comment]
@ragesoss it should be: you can just retrieve the original rev (+author name) with
the respective call (e.g. /rev_content/{article_title}/
<https://api.wikiwho.net/api/v1.0.0-beta/#!/1_-_Content_per_revision/get_rev_content_article_title>
),
only the parsing has to be adjusted in the whocolor server.
even more so: now one can in principle use the conflict view on live data
as well, bc. we deliver the additions/deletes (in/out).

I wanted to update the server, just didn't get around to it. If you beat me
to it, even better, pull requests to the repo at
https://github.com/wikiwho/whoCOLOR always welcome! (actually, we should
also use that one for future issue request etc. as jurkan is not really
involved anymore ;)

**Comment by ragesoss** [comment]
@wikiwho can you enable issues on the new repo?

FYI, I've started experimenting with a javascript replacement  for the whoColor server, so that my app can consume the wikiwho API directly. The original has shortcomings in terms of output that I'd like to eventually fix, and I'm more comfortable hacking and testing in JS than in PHP.

Here's where I'm at so far: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/2f458456c154771634dbfb7c0d3e18e7e6793d4c

If it becomes useful outside my app, I can break it out into a module. Feedback and advice welcome!

**Comment by wikiwho** [comment]
Issues are enabled now at the new repo. 

re: the whocolor server: cool, we'd like to help! Coincidentally, we actually also just started working on a new version of the server, although in Python, which will access the wikiwho data already internally on our server, without going through the  wikiwho API. Let me take a look at what you have done so far and then get back to you as soon as I can. 

P.S. closing the issue for now, will reopen the https issue at the new repo and hopefully solve it soon..
